[project]
name = "diu-thi-hieu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "nbconvert>=7.16.6",
    "pip>=25.0.1",
    "pylance>=0.24.1",
]
